using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// <para><strong>THIS CASS SHOULD  NO LONGER BE REFERENCED, PLEASE USE <c>RangeManager</c> INSTEAD</strong></para>
/// <para>Script for handling player movements.</para>
/// </summary>
/// <remarks>by Liam Riel</remarks>
public class MovementManager : MonoBehaviour
{
    public static MovementManager Instance;

    private void Awake()
    {
        Instance = this;
    }

    /// <summary>
    /// <para>Gets all tiles within a certain range of another tile</para>
    /// </summary>
    /// <param name="startTile">The tile to search from</param>>
    /// <param name="range">The maximum range to search for tiles away from startTile</param>
    /// <returns>A list with all found tiles in range of the starting tile</returns>
    public List<Tile> GetTilesInRange(Tile startTile, int range)
    {
        //List<Tile> tilesInRange = new();
        //Queue<Tile> visitQueue = new();

        //visitQueue.Enqueue(startTile);

        //while (visitQueue.TryDequeue(out Tile visitedTile))
        //{
        //    foreach (Tile neighbor in visitedTile.Neighbors.Where(t => !tilesInRange.Contains(t) && t.Walkable && DistanceBetween(startTile, t) <= range))
        //    {
        //        tilesInRange.Add(neighbor);
        //        visitQueue.Enqueue(neighbor);
        //    }
        //}

        //return tilesInRange;

        return RangeManager.GetTilesInRange(startTile, range);
    }

    public Dictionary<Tile, Tile> GetPathsInRange(Tile startTile, int range)
    {
        //Dictionary<Tile, Tile> tilePathsInRange = new();
        //Queue<Tile> visitQueue = new();

        //tilePathsInRange.Add(startTile, null);
        //visitQueue.Enqueue(startTile);

        //while (visitQueue.TryDequeue(out Tile visitedTile))
        //{
        //    foreach (Tile neighbor in visitedTile.Neighbors.Where(t => !tilePathsInRange.Keys.Contains(t) && t.Walkable && DistanceBetween(startTile, t) <= range))
        //    {
        //        tilePathsInRange.Add(neighbor, visitedTile);
        //        visitQueue.Enqueue(neighbor);
        //    }
        //}

        //// The start tile should not be 'reachable' from itself, b/c that could cause problems with path reconstruction later
        //tilePathsInRange.Remove(startTile);
        
        //return tilePathsInRange;

        return RangeManager.GetPathsInRange(startTile, range);
    }

    /*
    public int DistanceBetween(Tile fromTile, Tile toTile)
    {
        int xDiff = Math.Abs((int)fromTile.Position.x - (int)toTile.Position.x);
        int yDiff = Math.Abs((int)fromTile.Position.y - (int)toTile.Position.y);

        return xDiff + yDiff;
    }

    /// <summary>
    /// <para>Uses the dictionary created by GetPathsInRange to create the proper path to a tile</para>
    /// </summary>
    /// <param name="targetTile">The tile to find a path to</param>
    /// <param name="tilePaths">A dictionary of tiles (keys) and the tiles that precede them (value), generated by GetPathsInRange</param>
    /// <returns>A path to the target tile based on the path dictionary</returns>
    public List<Tile> ReconstructPath(Tile targetTile, Dictionary<Tile, Tile> tilePaths)
    {
        if (!tilePaths.ContainsKey(targetTile))
        {
            Debug.LogError("Path reconstruction failed, target tile is not a key in paths dictionary");
            return null;
        }

        List<Tile> path = new() { targetTile };

        while (tilePaths.TryGetValue(path[0], out Tile fromTile))
        {
            path.Insert(0, fromTile);
        }

        return path;
    }
    */
}
